name: Convert README to HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'

jobs:
  convert-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert README.md to index.html
      run: |
        pandoc README.md -o index.html --standalone \
          --template=./.github/scripts/template.html \
          --metadata title="My Personal Page"

    - name: Commit and push HTML
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update index.html from README"
        git push
