name: Convert README to HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
  workflow_dispatch:

# 添加权限声明
permissions:
  contents: write  # 明确授予写入权限

jobs:
  convert-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # 明确使用GITHUB_TOKEN
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert README.md to index.html
      run: |
        pandoc README.md -o index.html --standalone \
          --template=./.github/scripts/template.html \
          --metadata title="My Personal Page" \
          --wrap=none  # 禁止智能合并标题


    - name: Commit and push HTML
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update index.html from README (${{ github.event.inputs.reason }})"
        git push